Controllers/BillingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hospital_Management_System.Models;

namespace Hospital_Management_System.Controllers
{
    public class BillingsController : Controller
    {
        private HospitalDbContext db = new HospitalDbContext();

        // GET: Billings
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index()
        {
            return View(db.Billings.ToList());
        }

        // GET: Billings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Billing billing = db.Billings.Find(id);
            if (billing == null)
            {
                return HttpNotFound();
            }
            return View(billing);
        }

        // GET: Billings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Billings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BillID,PatientName,PatientAge,DoctorName,TotalBill")] Billing billing)
        {
            if (ModelState.IsValid)
            {
                db.Billings.Add(billing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(billing);
        }
        [Authorize]

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        // GET: Billings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Billing billing = db.Billings.Find(id);
            if (billing == null)
            {
                return HttpNotFound();
            }
            return View(billing);
        }

        // POST: Billings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Edit([Bind(Include = "BillID,PatientName,PatientAge,DoctorName,TotalBill")] Billing billing)
        {
            if (ModelState.IsValid)
            {
                db.Entry(billing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(billing);
        }

        // GET: Billings/Delete/5
        [Authorize]

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Billing billing = db.Billings.Find(id);
            if (billing == null)
            {
              
                return HttpNotFound();
            }
            return View(billing);
        }

        // POST: Billings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult DeleteConfirmed(int id)
        {
            Billing billing = db.Billings.Find(id);
            db.Billings.Remove(billing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/Doctors1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hospital_Management_System.Models;
using System.Web.Security;

namespace Hospital_Management_System.Controllers
{
    /*[Authorize]*/
    public class Doctors1Controller : Controller
    {
        public HospitalDbContext db = new HospitalDbContext();

        [Authorize]
        // GET: Doctors1
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index()
        {
            return View(db.Doctors.ToList());
        }
        [Authorize]
        // GET: Doctors1/Details/5
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }
        // GET: Doctors1/Create
        [Authorize]
        
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        public ActionResult PatientEdit()
        {
            return RedirectToAction("Edit","Patients");
        }



        // POST: Doctors1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.



        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DoctorID,DoctorName,Specialization,DoctorFees")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }


        // GET: Doctors1/Edit/5

        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.


        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DoctorID,DoctorName,Specialization,DoctorFees")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: Doctors1/Delete/5

        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors1/Delete/5

        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            var bill = db.Billings.Include(d=>d.doctor).Where(d=>d.doctor.DoctorID==id);
            db.Billings.RemoveRange(bill);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Doctors1/Create.cshtml
@model Hospital_Management_System.Models.Doctor
    @{ 
        Layout = "~/Views/Shared/_Layout1.cshtml";
    }

@{
    ViewBag.Title = "Add A Doctor";
}
<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background-image: url('../../content/images/11.jpg');
            background-position: center;
            background-size: 1360px 768px;
            background-color: #77c9d4;
            font-family: Arial, sans-serif;
        }
    </style>

</head>

<body>


  <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">

        <div class="container">-->

           @* @Html.ActionLink("We Care Hospital", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@

            <!--<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>

            </button>-->
       @*     <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <a href="~/Views/Shared/_Layout.cshtml"></a>
                <ul class="navbar-nav flex-grow-1">

                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("AdminLogin", "AdminLogin", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>

            </div>*@


        <!--</div>
        <div class="navbar-nav flex-grow-1">
            <ul class="">-->


             @* <li>@Html.ActionLink("Login", "Login", "Patients", new { area = "" }, new { @class = "nav-link fit1" })</li>
            </ul>*@
     @*   </div>*@
  @*      <div class="navbar-nav flex-grow-1">
            <ul class="">
                <li>@Html.ActionLink("Signup", "Create", "Patients", new { area = "" }, new { @class = "nav-link fit2" })</li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a>Welcome @User.Identity.Name</a></li>
                    <li>@Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { @class = "nav-link fit3" })</li>
                }
            </ul>

        </div>*@

    
    <div class="container body-content">
        <h2>Enter the Details</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Doctor</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.DoctorName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DoctorName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DoctorName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Specialization, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Specialization, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Specialization, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DoctorFees, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DoctorFees, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DoctorFees, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mt-2 mb-2">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Add New Doctor" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            <p>
                @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-dark" })
        </div>
        </p>

    </div>
</body>
</html>

Views/Doctors1/Delete.cshtml
@model Hospital_Management_System.Models.Doctor

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specialization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specialization)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorFees)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorFees)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-dark" })
        </div>
    }
</div>

Views/Doctors1/Details.cshtml
@model Hospital_Management_System.Models.Doctor

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specialization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specialization)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorFees)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorFees)
        </dd>

    </dl>
</div>
<p>
@*    @Html.ActionLink("Edit", "Edit", new { id = Model.DoctorID }) |*@
    @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-dark" })
</p>

Views/Doctors1/Edit.cshtml
@model Hospital_Management_System.Models.Doctor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DoctorID)

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Specialization, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Specialization, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Specialization, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorFees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorFees, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorFees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-dark" })
</div>

Views/Doctors1/Index.cshtml
@model IEnumerable<Hospital_Management_System.Models.Doctor>

@{
    ViewBag.Title = "Doctor List";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Doctor List</h2>


<p>
    @Html.ActionLink("🧑‍⚕Add New Doctor🧑‍⚕", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Edit Patient Details📝", "Index", "Patients", null, new { @class = "btn btn-warning" })
    @Html.ActionLink("🙇‍♂️Edit Appointments🙇‍♂️", "Index", "Billings", null, new { @class = "btn btn-dark" })
</p>
<table class="table">
    <tr>
        <th>

            @Html.DisplayNameFor(model => model.DoctorName)

        <th>
            @Html.DisplayNameFor(model => model.Specialization)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DoctorFees)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialization)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorFees)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.DoctorID }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Details", new { id = item.DoctorID }, new { @class = "btn btn-dark" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.DoctorID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
        <style>
            body {
                background-image: url('../../content/images/aabb.jpg');
                background-position: center;
                background-size: 1360px 768px;
                background-color: #77c9d4;
                font-family: Arial, sans-serif;
            }
        </style>




    }

</table>